FROM postgres:17

ENV POSTGRES_USER=forms_user
ENV POSTGRES_PASSWORD=forms_pass
ENV POSTGRES_DB=metrics_db


EXPOSE 5433

# docker build -t metrics-postgres .
# docker run -d --name metrics-db -p 5433:5433 metrics-postgres
